"""First migration

Revision ID: 9b591008ebcb
Revises:
Create Date: 2023-01-31 02:21:49.605495

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9b591008ebcb"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "review",
        sa.Column("review_id", sa.BigInteger(), nullable=True),
        sa.Column("tag_id", sa.Integer(), nullable=True),
        sa.Column("date_publish", sa.String(), nullable=True),
        sa.Column("rating", sa.Float(), nullable=True),
        sa.Column("sentiment_score", sa.Integer(), nullable=True),
        sa.Column("is_positive", sa.Boolean(), nullable=True),
        sa.Column("is_negative", sa.Boolean(), nullable=True),
        sa.Column("is_neutral", sa.Boolean(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("review")
    # ### end Alembic commands ###
